[package]
name = "push"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.85"
repository = "https://github.com/SisyphusAeolides/Push"
description = "Measured PID 1 and service supervisor for Arach OS"
build = "build.rs"

[features]
default = []
os-bin = []
fortran-policy = []
cosmic-boot = []

[dependencies]
libm = "0.2.16"
slope = { git = "https://github.com/SisyphusAeolides/Slope.git", rev = "b3decb53e71bb3c5d5fc55047451bcf9cef7eff9" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "push"
path = "src/main.rs"
required-features = ["os-bin"]
test = false

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
